namePrefix: dev-
resources:
  - ../../base
  
configMapGenerator:
  - name: nginx-config
    literals:
      - index.html=<html><body><h1>Welcome to DEV environment</h1></body></html>

patches:
  - path: replica-patch.yaml
    target:
      kind: Deployment
      name: nginx
